name: Release Package

on:
  push:
    branches: ["main"]
    paths-ignore: ["!README.md"]

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
      - run: npm run test
      - run: npm run cleanup
      - run: npm run build
      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Bump Package Version
        id: bumpVersion
        run: npm run bumpVersion

      - name: Check package version
        id: checkVersion
        run: |
          export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')
          echo $PACKAGE_VERSION # should print your version e.g. 1.0.0
          echo needs.build.steps.bumpVersion.output.results
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      # Commit changes
      - name: Commit changes
        run: |
          git add -A
          git commit -m "chore: release ${{ env.PACKAGE_VERSION }}"

  releaseNote:
    needs: build
    name: Create release notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: needs.build.steps.bumpVersion.output.results
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes

  publish-gpr:
    needs: releaseNote
    name: Publish package
    if: github.repository_owner == 'josh-uvi' #safeguard for forks
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: "@josh-uvi"
      - name: start ci
        run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
